apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: elastic
  namespace: elastic-stack
spec:
  version: 7.17.5
  count: 1
  elasticsearchRef:
    name: elastic
  config:
    elasticsearch.requestTimeout: 90000
    elasticsearch.shardTimeout: 90000
  podTemplate:
    spec:
      containers:
      - name: kibana
        resources:
          requests:
            memory: 1Gi
            cpu: 500m
          limits:
            memory: 2Gi
            cpu: 1000m
      nodeSelector:
        node.group: application
