apiVersion: v1
kind: Secret
metadata:
  name: elastalert-config-secret
  namespace: elastic-stack
type: Opaque
stringData:
  elastalert_config: |-
    rules_folder: /opt/elastalert/rules
    scan_subdirectories: true
    run_every:
      minutes: 5
    buffer_time:
      hours: 24
    es_host: elastic-es-http.elastic-stack
    es_port: 9200
    es_username: elastic
    es_password: c3b9dHyZx02rFL5Q64DtA978
    es_conn_timeout: 180
    writeback_index: elastalert
    use_ssl: True
    verify_certs: False
    alert_time_limit:
      hours: 6
