apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: filebeat-management
  namespace: elastic-stack
spec:
  type: filebeat
  version: 7.17.5
  config:
    filebeat.autodiscover.providers:
    - node: ${NODE_NAME}
      type: kubernetes
      hints.default_config.enabled: "false"
      templates:
      # INGRESS NGINX
      - condition.regexp.kubernetes.namespace: '^(ingress-nginx)'
        config:
        - paths: ["/var/log/containers/*${data.kubernetes.container.id}.log"]
          type: container
          fields_under_root: true
          fields.@metadata.index_reference: 'ingress-nginx'
          fields.@metadata.environment: 'management'
      # # KUBE SYSTEM
      # - condition.regexp.kubernetes.namespace: '^(kube-system)'
      #   config:
      #   - paths: ["/var/log/containers/*${data.kubernetes.container.id}.log"]
      #     type: container
      #     fields_under_root: true
      #     fields.@metadata.index_reference: 'kube-system'
      #     fields.@metadata.environment: 'management'
      # # ELASTIC STACK
      # - condition.regexp.kubernetes.namespace: '^(elastic-stack)'
      #   config:
      #   - paths: ["/var/log/containers/*${data.kubernetes.container.id}.log"]
      #     type: container
      #     fields_under_root: true
      #     fields.@metadata.index_reference: 'elastic-stack'
      #     fields.@metadata.environment: 'management'

      # # CATTLE-SYSTEM
      # - condition.regexp.kubernetes.namespace: '^(cattle-system)'
      #   config:
      #   - paths: ["/var/log/containers/*${data.kubernetes.container.id}.log"]
      #     type: container
      #     fields_under_root: true
      #     fields.@metadata.index_reference: 'cattle-system'
      #     fields.@metadata.environment: 'management'

    processors:
    - add_cloud_metadata: {}
    - add_host_metadata: {}
    output:
      logstash:
        hosts: ['logstash.elastic-stack:6000']
  daemonSet:
    podTemplate:
      spec:
        serviceAccountName: filebeat
        automountServiceAccountToken: true
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirstWithHostNet
        hostNetwork: true # Allows to provide richer host metadata
        containers:
        - name: filebeat
          securityContext:
            runAsUser: 0
            # If using Red Hat OpenShift uncomment this:
            #privileged: true
          volumeMounts:
          - name: varlogcontainers
            mountPath: /var/log/containers
          - name: varlogpods
            mountPath: /var/log/pods
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          resources:
            requests:
              memory: 256Mi
              cpu: 200m
            limits:
              memory: 256Mi
              cpu: 200m
        volumes:
        - name: varlogcontainers
          hostPath:
            path: /var/log/containers
        - name: varlogpods
          hostPath:
            path: /var/log/pods
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers