apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-pipeline-collector-snmp-config
  namespace: elastic-stack
data:
  logstash.conf: |-
    input {
      snmp {
        get => [".1.3.6.1.2.1.6.13"]
        hosts => [{host => "udp:172.21.214.103/161" community => "public" version => "2c"}]
        #mib_paths => ["/etc/logstash/mib/TCP-MIB.dic"]
        #walk => [".1.3.6.1.2.1.6.13.1"]
        oid_root_skip => 0
        interval => 90
        tables => [ {"name" => "tcpConnState" "columns" => [".1.3.6.1.2.1.6.13.1.1"]},
                    {"name" => "tcpConnLocalAddress" "columns" => [".1.3.6.1.2.1.6.13.1.2"]},
                    {"name" => "tcpConnLocalPort" "columns" => [".1.3.6.1.2.1.6.13.1.3"]},
                    {"name" => "tcpConnRemAddress" "columns" => [".1.3.6.1.2.1.6.13.1.4"]} ]
      }
    }

    #filters

    filter {
    split {
      field => "tcpConnState"
    }
    }

    filter {
    split {
      field => "tcpConnLocalAddress"
    }
    }

    filter {
    split {
      field => "tcpConnLocalPort"
    }
    }

    filter {
    split {
      field => "tcpConnRemAddress"
    }
    }

    output {
      elasticsearch {
        hosts => "${LOGSTASH_ES_HOST}"
        user => "${LOGSTASH_ES_USERNAME}"
        password => "${LOGSTASH_ES_PASSWORD}"
        index => "collector-snmp"
        cacert => "/usr/share/logstash/certs/ca.crt"
      }
    }
