apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: elastic-stack
spec:
  ports:
  - name: logstash
    port: 6000
    targetPort: 6000
    nodePort: 32060
  - name: siop
    port: 6001
    targetPort: 6001
    nodePort: 32061
  - name: logstash-metrics
    port: 9600
    targetPort: 9600
  selector:
    app: logstash
  type: NodePort

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elastic-logstash
  namespace: elastic-stack
  labels:
    app: logstash
spec:
  serviceName: logstash
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      terminationGracePeriodSeconds: 300
      containers:
      - name: logstash
        image: docker.elastic.co/logstash/logstash:7.17.5
        env:
        - name: LOGSTASH_ES_HOST
          value: https://elastic-es-http.elastic-stack:9200
        - name: LOGSTASH_ES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: elastic-es-elastic-user
              key: elastic
        - name: LOGSTASH_ES_USERNAME
          value: elastic
        - name: LOGSTASH_HOST
          value: 0.0.0.0
        - name: LOGSTASH_PORT
          value: "6000"
        - name: SIOP_PORT
          value: "6001"
        - name: ES_JAVA_OPTS
          value: "-Xms2048m -Xmx2048m"
        ports:
        - name: logstash 
          containerPort: 6000
        - name: siop
          containerPort: 6001
        resources:
          requests:
            memory: 2Gi
            cpu: 2000m
          limits:
            memory: 3Gi
            cpu: 2000m
        securityContext:
          privileged: true

        volumeMounts:
        - name: logstash-config
          mountPath: /usr/share/logstash/config/logstash.yml
          subPath: logstash.yml
        - name: logstash-pipeline-manager-config
          mountPath: /usr/share/logstash/config/pipelines.yml
          subPath: pipelines.yml
        - name: logstash-pipeline-config
          mountPath: /usr/share/logstash/pipeline/main/logstash.conf
          subPath: logstash.conf
        - name: logstash-pipeline-siop-config
          mountPath: /usr/share/logstash/pipeline/siop/logstash.conf
          subPath: logstash.conf
        - name: logstash-pipeline-elastalert-config
          mountPath: /usr/share/logstash/pipeline/elastalert/logstash.conf
          subPath: logstash.conf
        - name: logstash-pipeline-collector-snmp-config
          mountPath: /usr/share/logstash/pipeline/collector-snmp/logstash.conf
          subPath: logstash.conf
        - name: elastic-es-http-certs-public
          mountPath: "/usr/share/logstash/certs/"
          readOnly: true

      nodeSelector:
        node.group: application

      volumes:
      - name: logstash-config
        configMap:
          name: logstash-config
      - name: logstash-pipeline-manager-config
        configMap:
          name: logstash-pipeline-manager-config
      - name: logstash-pipeline-config
        configMap:
          name: logstash-pipeline-config
      - name: logstash-pipeline-siop-config
        configMap:
          name: logstash-pipeline-siop-config
      - name: logstash-pipeline-elastalert-config
        configMap:
          name: logstash-pipeline-elastalert-config
      - name: logstash-pipeline-collector-snmp-config
        configMap:
          name: logstash-pipeline-collector-snmp-config
      - name: elastic-es-http-certs-public
        secret:
          secretName: elastic-es-http-certs-public
          items:
          - key: ca.crt
            path: ca.crt
